name: wallet
description: ROI Wallet

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2
  validators: ^3.0.0
  auto_route: ^3.1.3
  dio: ^4.0.3
  retrofit: ">=3.0.0 <4.0.0"
  pretty_dio_logger: ^1.1.1
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  injectable: ^1.5.0
  cached_network_image: ^3.1.0+1
  flutter_svg_provider: ^0.1.11
  flutter_secure_storage: ^5.0.2
  json_annotation: ^4.3.0
  connectivity_plus: ^2.0.3
  url_launcher: ^6.0.13
  modal_bottom_sheet: ^2.0.0

  ## blockchain dependencies
  fast_base58: ^0.2.1
  hash: ^1.0.4
  dart_bech32: ^2.0.0
  elliptic: ^0.3.5
  pointycastle: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.19.3
  build_runner:
  flutter_gen_runner:
  retrofit_generator: ">=3.0.0 <4.0.0"
  mobx_codegen: ^2.0.4
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  auto_route_generator: ^3.1.0
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2
  mock_web_server: ^5.0.0-nullsafety.1
##  lint: ^1.7.2

dependency_overrides:
  test_api: 0.4.2

## https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/generated/
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors-light.xml
      - assets/color/colors-dark.xml

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/
    - assets/

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en

flutter_native_splash:
  background_image: "assets/images/img_splash.png"

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
## https://github.com/SimpleBoilerplates/Flutter/blob/master/derry.yaml
## scripts: derry.yaml