name: wallet
description: EZChain Wallet

publish_to: none

version: 1.0.1+2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2
  validators: ^3.0.0
  auto_route: ^3.2.0
  dio: ^4.0.4
  retrofit: ">=3.0.0 <4.0.0"
  pretty_dio_logger: ^1.1.1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  get_it: ^7.2.0
  injectable: ^1.5.0
  cached_network_image: ^3.1.0+1
  flutter_svg_provider: ^0.1.11
  flutter_secure_storage: ^5.0.2
  json_annotation: ^4.3.0
  connectivity_plus: ^2.3.0
  url_launcher: ^6.0.13
  modal_bottom_sheet: ^2.0.0
  flutter_switch: ^0.3.2
  freezed_annotation:
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  share_plus: ^4.0.4
  local_auth: ^1.1.11
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_crashlytics: ^2.4.4
  async: ^2.8.2

  ## crypto dependencies
  fast_base58: ^0.2.1
  hash: ^1.0.4
  dart_bech32: ^2.0.0
  elliptic: ^0.3.5
  pointycastle: ^3.4.0
  bip39: ^1.0.6
  hdkey: ^0.0.1
  web3dart: ^2.3.5
  sha3: ^0.2.0
  eventify: ^1.0.0
  decimal: ^2.1.0

dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.20.0
  build_runner:
  flutter_gen_runner:
  retrofit_generator: ^4.0.1
  mobx_codegen: ^2.0.5+2
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  auto_route_generator: ^3.1.0
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2
  mock_web_server: ^5.0.0-nullsafety.1
  freezed:
##  lint: ^1.7.2

#dependency_overrides:
#  test_api: 0.4.2
#  matcher: 0.12.11

## https://pub.dev/packages/flutter_gen
flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/generated/
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors-light.xml
      - assets/color/colors-dark.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/dev.env

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400
flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en

flutter_native_splash:
  background_image: "assets/images/img_splash.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_app.png"

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
## https://github.com/SimpleBoilerplates/Flutter/blob/master/derry.yaml
## scripts: derry.yaml