# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "EZChain-iOS"

  before_all do |lane, options|
  end

  lane :ios_internal_alpha do |options|
    bump_version()
    build_app(
        scheme: "Runner",
        archive_path: "./build/Runner.xcarchive",
        export_method: "development",
        output_directory: "./build/Runner"
    )
    firebase_app_distribution(
        app: ENV["FIREBASE_IOS_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        groups: "ios_testers",
        release_notes: change_log_from_git(),
        ipa_path: "./build/Runner/Runner.ipa"
    )
  end

  private_lane :bump_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_IOS_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
    increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
  end

  private_lane :change_log_from_git do |options|
      count = (options[:count] ? options[:count] : 10)
      changelog_from_git_commits(
          commits_count: count,
          pretty: "- (%ae) %s",
          date_format: "short",
          merge_commit_filtering: "exclude_merges"
      )
  end

  after_all do |lane, options|
  end

end
