# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "EZChain-iOS"

  before_all do |lane, options|
  end

  lane :ios_internal_alpha do |options|
    build_app(
        scheme: "Runner",
        archive_path: "./build/Runner.xcarchive",
        export_method: "development",
        output_directory: "./build/Runner"
    )
    firebase_app_distribution(
        app: ENV["FIREBASE_IOS_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        groups: "developer",
        release_notes: "EZChain iOS",
        ipa_path: "./build/Runner/Runner.ipa"
    )
  end

  lane :ios_test do
    UI.message "FIREBASE_IOS_APP_ID = #{ENV["FIREBASE_IOS_APP_ID"]}"
  end

  after_all do |lane, options|
  end

end
