const LATESTCODEC = 0;

const SECPFXID = 0;

const SECPXFEROUTPUTID = 7;

const SUBNETAUTHID = 10;

const SECPOWNEROUTPUTID = 11;

const STAKEABLELOCKOUTID = 22;

const SECPINPUTID = 5;

const STAKEABLELOCKINID = 21;

final LOCKEDSTAKEABLES = [STAKEABLELOCKINID, STAKEABLELOCKOUTID];

const BASETX = 0;

const ADDVALIDATORTX = 12;

const ADDSUBNETVALIDATORTX = 13;

const ADDDELEGATORTX = 14;

const CREATECHAINTX = 15;

const CREATESUBNETTX = 16;

const IMPORTTX = 17;

const EXPORTTX = 18;

const ADVANCETIMETX = 19;

const REWARDVALIDATORTX = 20;

const SECPCREDENTIAL = 9;

const ASSETIDLEN = 32;

const BLOCKCHAINIDLEN = 32;

const SYMBOLMAXLEN = 4;

const ASSETNAMELEN = 128;

const ADDRESSLENGTH = 20;
